### ISSUE TITLE
Unable to add new ASCO abstract source

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#1022]
While trying to curate this evidence (https://meetings.asco.org/abstracts-presentations/195666) I found that the source field, on either the Add Evidence or Add Source page, is not able to identify abstract ID 195666. This may be related to #942.

I also noticed that on the Sources browse grid there are display issues when filtering on the source, and when typing in a specific source ID a match is displayed that is not a match to the ID entered (see below).

![image](https://github.com/griffithlab/civic-v2/assets/3093548/70556cf5-9be2-4f74-8c18-5169102a9d5a)

**Comment by acoffman** [comment]
Yeah, ASCO removed the API we were previously using and their new site is behind cloudflare bot protection so we can't scrape it directly any longer. Until we manage to figure out a way to work around that, it will unfortunately remain broken. We have some ideas though!

We will take a look at the filtering issue though, that's strange and unexpected.

**Comment by acoffman** [comment]
#1105 should fix the filtering issue mentioned here. Ongoing issue with the ASCO API will be tracked in #942
