### ISSUE TITLE
Variant/MP Data duplication

### ISSUE THREAD

**Issue by shencangsheng** [griffithlab/civic-v2#1052]
Variant ID: 1026/2909 BCR::ABL Y253F 
MP ID: 1000/2778 ABL1 BCR::ABL Y253F

Expect Variant name unique
Expect MP name unique

from latest tsv file 
![image](https://github.com/griffithlab/civic-v2/assets/67856731/e65c09a8-4d01-48a1-a78b-f86f1d8d9b88)
![image](https://github.com/griffithlab/civic-v2/assets/67856731/eae17224-46b4-499e-821b-2e6d34795613)

**Comment by susannasiebert** [comment]
Thank you for bringing this issue to our attention. I have relayed it to our editors for cleanup of the duplicate. If you have a CIViC account, you are welcome to flag such entries directly in the CIViC interface in the future.
