### ISSUE TITLE
Features: Gene: Internal Server Error (500)

### ISSUE THREAD

**Issue by sumirp** [griffithlab/civic-v2#1075]
1. Go to Features tab on civicdb.
2. Click on any gene.
3. The summary page opens without any data and the console shows as internal server error.
<img width="1257" alt="Screenshot 2024-06-27 at 6 21 35 PM" src="https://github.com/griffithlab/civic-v2/assets/46551795/6b925df9-0baa-4e85-b87d-aa591759836b">

**Comment by acoffman** [comment]
Hi @sumirp, thanks so much for the report!

It looks like this was an issue with our MyGene.info integration. Their API is returning a 500 error and we weren't properly catching the issue.

The error is properly handled now and the page should load for you, however the MyGene.info box will not show until the errors on their end are resolved.

Thanks again,

Adam

**Comment by sumirp** [comment]
Thank you @acoffman for this information.
