### ISSUE TITLE
Add new variant type ahead appears to be broken for genes

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#1118]
<img width="557" alt="Screen Shot 2024-10-01 at 12 37 35 PM" src="https://github.com/user-attachments/assets/6ee57d0a-21d9-4f95-8cfe-4cad6d581ec0">

Trying to create a new variant VHL S139C (c.416C>G) to change this variant into a complex MP https://civicdb.org/variants/4245/summary But type ahead won't let me pick VHL.

**Comment by kkrysiak** [comment]
This seems to be a broader issue with the type ahead. To quote Jason from Slack "Obi and I are seeing some odd fusions names. Related to (but not limited to) the following MPs 415, 5038, and 4894.  When I go to make a revision at the variant level, the type ahead isnt working and cannot change from gene to fusion"

**Comment by susannasiebert** [comment]
The typeaheads don't seem to be firing at all. There are no graphql queries being sent as someone is typing into these fields, as far as I can tell
