### ISSUE TITLE
Fusion Variants Missing from VariantSummaries tsv

### ISSUE THREAD

**Issue by nlfortier** [griffithlab/civic-v2#1123]
A large number of fusion variants that previously had entries in the VariantSummaries.tsv file have now been removed as of October. All of the removed variants appear to be gene fusions. These variants had variant summary information in the previous release and can be still be looked up using both the website and the GraphQL API. 

Below is a complete list of the removed variant ids:
1, 5, 30, 31, 52, 53, 54, 108, 164, 184, 195, 209, 273, 285, 286, 287, 431, 432, 448, 449, 450, 500, 501, 503, 513, 514, 520, 524, 535, 567, 568, 571, 574, 576, 599, 617, 618, 626, 656, 657, 706, 717, 722, 742, 774, 780, 782, 783, 800, 801, 830, 1277, 1278, 1282, 1687, 2166, 2178, 2179, 2202, 2203, 2218, 2227, 2229, 2286, 2287, 2289, 2393, 2394, 2395, 2396, 2571, 2575, 2581, 2582, 2583, 2593, 2630, 2639, 2640, 2660, 2661, 2663, 2678, 2682, 2743, 2769, 2770, 2772, 2846, 2847, 2848, 2849, 2850, 2859, 2860, 2861, 2862, 2863, 2864, 2865, 2883, 2894, 2941, 2952, 2968, 2969, 2971, 2972, 2974, 2975, 2976, 2977, 2992, 3126, 3140, 3158, 3214, 3251, 3252, 3268, 3269, 3270, 3271, 3272, 3287, 3359, 3465, 3622, 3700, 3701, 3702, 3730, 4000, 4001, 4241, 4252, 4253, 4299, 4300, 4327, 4337, 4405, 4496, 4528, 4532, 4533, 4534, 4535, 4536, 4546, 4577, 4602, 4612, 4626, 4628, 4646, 4652, 4690, 4796, 4797, 4798, 4908, 4941, 4972, 4973, 4974, 4975, 4995, 4999, 5013

**Comment by acoffman** [comment]
Hi,

Thanks so much for your detailed report!

This past month we rolled out a more formalized fusion variant model. This resulted in some incompatibilities with the existing TSV format and thus, they were not included. We have an open PR (#1122) to rework the TSV format to accommodate our new Fusion model (as well as Factor variants) and expect it to go out in the next few days. I will follow up on this issue when the change is live.

Thanks!
Adam

**Comment by rob-fisher** [comment]
@acoffman Hi Adam, are you able to advise when you expect the fix to be released and start appearing in the nightly data releases?
Thanks, Rob

**Comment by acoffman** [comment]
Hi @rob-fisher, the fix has been merged and will go out in our next deploy. This will likely be today or tomorrow, I will follow up on this issue when its live!

**Comment by acoffman** [comment]
These changes have been deployed and I have triggered a rebuild of the nightly TSVs, so the updated format that includes Fusion and Factor variants should now be available. Please let me know if you have any questions!

Thanks,
Adam
