### ISSUE TITLE
Decide on metrics to display on user and organization pages

### ISSUE THREAD

**Issue by acoffman** [griffithlab/civic-v2#182]
What metrics should we show? What should be included in the counts (accepted/submitted/rejected? child orgs? etc)

**Users**
| Metric Name  | Metric description | Tooltip/helptext
| ------------- | ------------- |------------ |
| Submitted Evidence | Count of all evidence submitted by this user regardless of current status (omit rejected?)  | Total number of evidence items this user has submitted.

**Orgs**
| Metric Name  | Metric description | Tooltip/helptext
| ------------- | ------------- |------------ |
| Submitted Evidence | Count of all evidence submitted by the org (and child orgs?) regardless of current status (omit rejected?)  | A count of evidence items submitted by members of this org and all of its child organizations

**Comment by susannasiebert** [comment]
Folks seem to be happy with the stats we came up with.
