### ISSUE TITLE
Coordinate Labels

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#278]
<img width="765" alt="Screen Shot 2022-03-24 at 2 44 26 PM" src="https://user-images.githubusercontent.com/8527125/159997989-12d895b2-a94e-4bac-94b5-a704756d4b4e.png">

JAK2 V617F is not a fusion so I don't understand this 5' Coordinates label
http://34.209.114.226/variants/64/summary

**Comment by susannasiebert** [comment]
I think there has been a mix up on our end. Are 3' coordinates the primary coordinates and 5' coordinates secondary coordinates then?
