### ISSUE TITLE
Links to Flags/Revisions/Comments in EID pop-ups not working

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#283]
When I mouse over an EID on the Evidence page it displays information about that EID including how many flags, revisions and comments there are. Those three entities at the bottom of the pop-up seem to be clickable but the links aren't working.

Similar links to flags/revisions/comments on mouse-over pop-ups for other entities such as a gene and variant seem to be linking to the correct pages.

**Comment by acoffman** [comment]
Nice catch thanks! Fixed in the referenced commit.
