### ISSUE TITLE
Disallowed host from DOID link?

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#287]
https://staging.civicdb.org/diseases/368/summary

Clicking on the DOID link in the top right I was redirected to: https://www.disease-ontology.org/?id=DOID:0060079

I got the following error:
![Screen Shot 2022-03-28 at 10 05 35 AM](https://user-images.githubusercontent.com/8527125/160428726-0a721292-e10a-4b1b-ad2b-fa53b487a7e9.png)

I'm not clear if this is an issue with my computer or potentially things blocked by washu.

**Comment by susannasiebert** [comment]
I'm not on a VPN and it's working fine for me.

**Comment by kkrysiak** [comment]
This worked for me this morning. No clue what happened. Thanks for looking into it.
