### ISSUE TITLE
Notifications won't load (very large list)

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#289]
https://staging.civicdb.org/users/6/notifications

I have more than >16k notifications, which I don't anticipate to be common, but my notifications won't load.

**Comment by susannasiebert** [comment]
We think that this is related to the filters since you have so many entities related to your notifications. We are planning on reducing the number of entities available to filtering to the top 10 or so, which should hopefully make this load faster (see #271).

**Comment by susannasiebert** [comment]
This might actually be unrelated to #271 after all. In my own notifications I get a "Cannot return null for non-nullable field EventSubjectWithCount.subject" graphql query. I expect this is the same error KK might be encountering.

**Comment by kkrysiak** [comment]
I just get a spinning wheel.
![Screen Shot 2022-03-30 at 3 02 56 PM](https://user-images.githubusercontent.com/8527125/160921154-84c76756-3907-457b-a2e6-3e770108842b.png)

Errors in dev tools window
![Screen Shot 2022-03-30 at 3 02 20 PM](https://user-images.githubusercontent.com/8527125/160921061-54380f0c-b745-4d1d-bed0-4772bd2964ca.png)

**Comment by acoffman** [comment]
This should be working now, but let us know if you run into any other issues!

**Comment by kkrysiak** [comment]
works now!
