### ISSUE TITLE
MyVariant.Info tabs off-by one error

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-v2#328]
Clicking the tabs doesn't open to the correct content

**Comment by acoffman** [comment]
I can't reproduce this, did you have to do something first to get  it to happen?

**Comment by susannasiebert** [comment]
To reproduce:
- Browse to https://staging.civicdb.org/variants/12/summary
- Click on the MyVariantInfo gnomAD (2.1.1) tab. It opens the ClinVar tab, not the gnomAD tab
