### ISSUE TITLE
Newly added EID not being displayed

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#330]
When I try to navigate to an EID that I just submitted it takes me to a blank page. I tried accessing from the Evidence browse grid and the quick search, both of which showed the EID (EID8956) was there. I tried several hard refreshes and I see what looks like an EID card quickly flash on the screen but then disappear.

**Comment by cgrisdale** [comment]
Also, the EID mouse-over pop-up for EID8956 is just a blank white box.

**Comment by acoffman** [comment]
Causal error is "cannot return null for non nullable type, source.citation" related to not fetching the citation from pubmed. Should be a straightforward fix.

**Comment by arpaddanos** [comment]
I note that what seems to be happening is that when clicking on an EID created using the V2 interface I get the blank screen, and this seems to be from anywhere (say from the activity feed or when on a person's page) but when I click on an older EID made with V1.5 it seems to work and take me to the EID page

**Comment by acoffman** [comment]
This was related to the asynchronous fetching of the source details not being hooked up on staging and is now resolved.
