### ISSUE TITLE
EID revision comment requirement

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#331]
When reviewing EID revisions I'm able to accept them without adding a comment, but need to comment to reject. I think we either want the reverse behaviour or to require a comment for accepting or rejecting.

**Comment by acoffman** [comment]
I believe this is actually the intended behavior, as in many cases a comment for accepting a revision is sort of redundant "Yes, I agree" whereas rejecting may require some explanation about what was wrong. I will add it to the meeting agenda to confirm with the group though.

**Comment by kkrysiak** [comment]
Yeah, this is the intended behavior. Rejections require a comment. Accept, hopefully it's just correct and we are good.
