### ISSUE TITLE
Display issue in user evidence grid and evidence queue

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#337]
In the evidence grid of my user page there is a vertical black bar at the far right side that covers the star image except when I mouse over that row. I see similar minor display issues in the Evidence and Assertion Queue grids.

![image4493](https://user-images.githubusercontent.com/3093548/161140797-3c5e7166-3cc5-4373-8b71-698cd274c541.png)

**Comment by susannasiebert** [comment]
I think you're running into the same overflow issue mentioned in #307
