### ISSUE TITLE
Can't submit source suggestion

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#345]
I click the button but nothing happens.
<img width="1789" alt="Screen Shot 2022-04-01 at 9 45 40 AM" src="https://user-images.githubusercontent.com/8527125/161287073-610d1901-f32d-4b48-a492-b91373a91438.png">

**Comment by jmcmichael** [comment]
@acoffman @susannasiebert Those `Cannot read properties of undefined...` look like the errors thrown by the typeahead when it encounters undefined fields in `sourceTypeahead` query's responses.
