### ISSUE TITLE
Should Source Suggestion be clickable in the activity feed?

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#347]
All other entities are so this would be more intuitive. Not sure if that is possible. Make SSIDs clickable.
<img width="399" alt="Screen Shot 2022-04-01 at 9 55 04 AM" src="https://user-images.githubusercontent.com/8527125/161288852-4b6bf73c-bdb4-451d-a981-116dc77d5359.png">

**Comment by acoffman** [comment]
They should appear in a tag, but there is currently not a "source suggestion" page for such a click to lead to. We could link to the source page itself though and display `new` suggestions on it.
