### ISSUE TITLE
Drug term search-ahead not acting as expected

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-v2#361]
In the add EID and add AID forms, putting in the text for `Trastuzumab` does not get to the desired drug `Trastuzumab` as it does in v1.5 seen below:
<img width="996" alt="Trastuzu" src="https://user-images.githubusercontent.com/13948978/161296992-f02cd119-fb3d-42ff-9a2b-48a41517237b.png">
<img width="1208" alt="TrastuzuEID" src="https://user-images.githubusercontent.com/13948978/161297005-14b8932d-6ab9-4601-a6ef-375f71d28216.png">

**Comment by arpaddanos** [comment]
In V1.5
<img width="1218" alt="DrugAdd1" src="https://user-images.githubusercontent.com/13948978/161297224-0c153bc6-74f5-45e4-b067-aa803f63c369.png">

**Comment by susannasiebert** [comment]
This was already reported in #338 and fixed in #339
