### ISSUE TITLE
Drug type ahead not acting as expected

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-v2#363]
When adding new Predictive EID or AID in V2, the drug typeahead is not as expected. In this example for Trastuzumab from v1.5 we expect this:
<img width="996" alt="Trastuzu" src="https://user-images.githubusercontent.com/13948978/161297856-99e97ca8-75ea-444b-9b16-c8110af97e1a.png">

**Comment by arpaddanos** [comment]
Instead currently I get this for EID:
<img width="1208" alt="TrastuzuEID" src="https://user-images.githubusercontent.com/13948978/161297966-fc8c148e-617e-43ee-9c54-322746f8b7c9.png">
Or for AID
<img width="1218" alt="DrugAdd1" src="https://user-images.githubusercontent.com/13948978/161298006-92b7d8ce-d801-4cec-b425-68957573f6d9.png">

**Comment by susannasiebert** [comment]
This was already reported in https://github.com/griffithlab/civic-v2/issues/338 and #361 and fixed in https://github.com/griffithlab/civic-v2/pull/339. This should be live any moment now.

**Comment by arpaddanos** [comment]
Also unable to select the desired drug "Trastuzumab" and seem forced to choose something wrong which contains the word instead:
<img width="1274" alt="choice" src="https://user-images.githubusercontent.com/13948978/161298748-bfac50f8-9389-4718-8b9e-c15a447d459d.png">
