### ISSUE TITLE
Remove N/A from Variant-types browse?

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#365]
I realize we add N/A to some of these but clicking on it does not go anywhere: https://staging.civicdb.org/variant-types/183/summary 

Otherwise, the "view on SO" also goes nowhere (as you'd expect).

Consider removing from table or otherwise ensure that the table with all variants that have type N/A to load?
<img width="1295" alt="Screen Shot 2022-04-01 at 11 44 52 AM" src="https://user-images.githubusercontent.com/8527125/161306851-eabc1a8e-1837-4180-8f9d-35a27949caa1.png">

**Comment by acoffman** [comment]
There is actually a page for the N/A variant type; it just wasn't being linked correctly. Its fixed now.
