### ISSUE TITLE
Assertion grid not loading on EID page

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#395]
When looking at an EID, the Assertion grid at the bottom tries to load indefinitely.

![image](https://user-images.githubusercontent.com/3093548/162272388-83b68c84-5947-4908-9e33-a04a8a5ad204.png)

**Comment by susannasiebert** [comment]
We just pushed a fix for that. Should be up on staging momentarily.

**Comment by susannasiebert** [comment]
Fixed.

**Comment by cgrisdale** [comment]
Yes, it's working for me now.
