### ISSUE TITLE
Delay in displaying correct PubMed source on newly created EID

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#426]
After submitting a new EID I noticed that the Source was shown as 'PubMed:null'. After about 15-20mins the correct Source was being displayed. This does not happen when I submit an EID with a source that has already been used in CIViC.

**Comment by acoffman** [comment]
I noticed this too, and it should be corrected going forward. Also, thanks for being the first to submit an EID on the new production site!
