### ISSUE TITLE
Add Evidence button on Suggested Source not working

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#435]
In the Source Suggestion queue there is a '+' in the Actions column that says 'Curate an Evidence Item from this Source Suggestion'. Clicking on the '+' does not take me to an add evidence form.

**Comment by acoffman** [comment]
Curating from a source isn't supported just yet; its on our immediate post-launch task list so its coming soon. In the meantime, we should disable the button to avoid confusion. Thanks for the report!

**Comment by susannasiebert** [comment]
The button has been disabled.

**Comment by susannasiebert** [comment]
@cgrisdale you should now be able to curate evidence items from a source suggestion.

**Comment by cgrisdale** [comment]
I'm now able to get to an Add Evidence form by clicking the '+' on a suggested source.
Thanks
