### ISSUE TITLE
Revise evidence form doesn't allow submit until mouse away from comment

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-v2#443]
When I make a change to an existing EID (e.g., change the variant name) I am required to also add a comment of certain length. That is as we want it. But, even when I complete a sufficient comment, the submit button remains greyed out until I click mouse outside of the comment box. This is not intuitive. I think in v1, as soon as comment reached sufficient length the submit button would activate. 
<img width="1248" alt="Screen Shot 2022-04-12 at 5 06 03 PM" src="https://user-images.githubusercontent.com/1638042/163064819-49ce1ed9-5bbe-424b-acde-7064ea5477c6.png">

**Comment by arpaddanos** [comment]
A similar issue we seem to be encountering is that when submitting an EID you need to click into the comment field in order to get the Submit button to become active. This should not be required as comments are not required for submitting an EID.
