### ISSUE TITLE
Issue with loading more rows in Activity feed

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#448]
About 15-20 seconds after loading more rows in the Activity feed the additional rows disappear and the page jumps back to the top and displays the default number of rows again. This does not seem to be a problem when loading additional rows in Evidence and Assertion grids.

**Comment by susannasiebert** [comment]
This is related to the auto-refreshing, which refetches the query to keep things up-to-date. But that always goes back to the initial number of items. We'll investigate if there is a way to get around this.
