### ISSUE TITLE
On the activity feed (and maybe other places) kkrysiak's user image cannot be loaded

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-v2#451]
404 not found from `https://civicdb.org/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhOWEY0WW5oNmNXNW1hemh5T0RrM2NIZ3phR3RuYVRNNWQyeHhjd1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpTldsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SWpZdWFuQm5JanNnWm1sc1pXNWhiV1VxUFZWVVJpMDRKeWMyTG1wd1p3WTdCbFE2RVdOdmJuUmxiblJmZEhsd1pVa2lEMmx0WVdkbEwycHdaV2NHT3daVU9oRnpaWEoyYVdObFgyNWhiV1U2Q214dlkyRnMiLCJleHAiOiIyMDIyLTA0LTEzVDE3OjUzOjM1LjM1NFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--cbc529f2e2a87d0d4a5c6f2ad6bd6b5fd36b5c5a/6.jpg`

All other user images appear to load ok

**Comment by kkrysiak** [comment]
It is available on my user page and in the popover, just not the tiny one as far as I can see.
![Screen Shot 2022-04-14 at 1 48 57 PM](https://user-images.githubusercontent.com/8527125/163457117-89654c94-566f-479e-ae39-56171bb7a254.png)
