### ISSUE TITLE
Comment Markdown not shown on import

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#488]
https://civicdb.org/assertions/3/comment

Full URL is shown.

<img width="981" alt="Screen Shot 2022-04-21 at 2 04 25 PM" src="https://user-images.githubusercontent.com/8527125/164534721-bdc5e1f8-b110-479a-9b21-023c81011ff4.png">
s

**Comment by acoffman** [comment]
Autolinking is working again
