### ISSUE TITLE
Nested pop-up shown for some entities but not others

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#492]
I noticed that while mousing over entities/tags in a pop-up typically doesn't produce additional pop-ups, in the case of Comments you can get a second nested pop-up (see screenshot). I tried mousing over genes and variants within pop-ups and nothing happens. I'm not sure which behaviour is expected.
Also, it seems like mousing over EID tags within a pop-up tries to create a second pop-up but it's just a small blank box.

![image](https://user-images.githubusercontent.com/3093548/164817220-2ce9720f-1d29-471a-a2b8-0d74945e9e88.png)

![image](https://user-images.githubusercontent.com/3093548/164817295-5aafa6a2-6f2d-492a-a1ed-f33fc2b06a17.png)

**Comment by susannasiebert** [comment]
We intentionally turned them off because it can lead to weird display issues. We must've forgotten to do so in the cases you mentioned. I will look into it.
