### ISSUE TITLE
Submit button not activated when filling out all fields for Source Suggestion

### ISSUE THREAD

**Issue by jsaliba10** [griffithlab/civic-v2#504]
I am unable to submit a source suggestion. I filled out all the fields, but the submit button is still greyed out.
<img width="1792" alt="Screen Shot 2022-04-27 at 3 02 10 PM" src="https://user-images.githubusercontent.com/59739804/165622098-0f5e048b-f40e-4c49-85f0-e98311fe1903.png">

**Comment by susannasiebert** [comment]
I believe you need to click the “add source” button first

**Comment by jsaliba10** [comment]
Ok that worked.    But I think there is a lag going on related to entering in the comment. 

So when I type the comment in, the button is still greyed out.  I either need to click out of the comment by clicking the mouse elsewhere on the page or wait a bit for the button to be active. 

<img width="1792" alt="Screen Shot 2022-04-27 at 3 30 03 PM" src="https://user-images.githubusercontent.com/59739804/165625884-2d64591f-c461-46be-a594-396a7f0983fa.png">


or if I enter the comment in first, then enter the source, and click add source - the button remains grey. I need to click on the comment field to activate the button.

**Comment by susannasiebert** [comment]
Yeah, that’s a known problem on almost all of the forms. It’s on our priority list of things to fix.

**Comment by jsaliba10** [comment]
Got it.   Though now my source is showing up as null in the queue...

<img width="1792" alt="Screen Shot 2022-04-27 at 3 36 26 PM" src="https://user-images.githubusercontent.com/59739804/165626658-f2452a4b-e261-4a51-9639-a7faa31f24d3.png">

**Comment by acoffman** [comment]
Source fetching should be fixed; that was related to me fiddling with the schedule task config as we port over our V1 background jobs, sorry about that.

**Comment by jsaliba10** [comment]
looks good.  thank you
