### ISSUE TITLE
In activity feed, combine events related to revisions from the same revision set

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-v2#512]

**Comment by susannasiebert** [comment]
| Activity | Subject | Actions/Events | Created (Non-Event) Entities | Linked Entities
| ------- | ------- | ---- | ---- | --- |
| Comment | EID / Assertion / Variant / Gene / Flag / Revision / Variant Group / Revision Set (?) | commented | Comment | Comment
| Suggest Revisions | EID / Assertion / Variant / Gene / Variant Group | revision set created, revision suggested (1+), commented | Revision Set, Revision (1+), Comment | Revision Set, Revision (1+), Comment
| Accept Revisions | EID / Assertion / Variant / Gene / Variant Group | revision accepted (1+), revision superseded (0+), commented (optional) | Comment (optional) | Revision (1+), Comment (optional)
| Reject Revisions | EID / Assertion / Variant / Gene / Variant Group |  revision rejected (1+), commented  | Comment | Revision (1+), Comment
| Submit EID | EID | submitted, commented | EID, Comment | Comment
| Moderate EID | EID | accepted / rejected / reverted | None | None
| Suggest Publication | SourceSuggestion | publication suggested, commented | SourceSuggestion, Comment | Source Suggestion, Comment
| Flag Entity | EID / Assertion / Variant / Gene / Variant Group | flagged, commented | Flag, Comment | Flag, Comment
| Resolve Flag | EID / Assertion / Variant / Gene / Variant Group | flag resolved, commented | Comment | Flag, Comment
| Submit Assertion | Assertion | assertion submitted, commented | Assertion, Comment | Comment
| Moderate Assertion | Assertion | assertion accepted / assertion rejected /assertion reverted | None | None
| Deprecate Variant | Variant | deprecated variant, deprecated molecular profile | None | Molecular Profile (1+)
| Update Source Suggestion Status | SourceSuggestion | requeued source suggestion / curated source suggestion / rejected source suggestion | None | None

**Comment by acoffman** [comment]
"Special Case Comments" that need porting to Activity "notes"

- [ ] Source Suggestion `initial_comment`
- [ ] Source Status Update `reason`
- [ ] Flag open/resolve comments
- [ ] Revision comments (create/reject/accept)
