### ISSUE TITLE
CIViC URLs Change

### ISSUE THREAD

**Issue by wrightmw** [griffithlab/civic-v2#534]
We have found that links to CIViC from ClinGen's Variant Curation Interface (VCI) are now broken. It appears your URLs have changed. 

For example, the VCI is currently directing to the URL: https://civicdb.org/events/genes/19/summary/variants/33/summary#variant , but it looks like CIViC now uses https://civicdb.org/variants/33/summary

It seems like there is a simple transposition from the old to new URLs (as in the example above) but we'd prefer to make sure before we commit developer time to updating our links. Do you have any documentation or release notes on this change that you can direct us to?

**Comment by susannasiebert** [comment]
Hi Matt,

We generally recommend for direct linking to use single-identifier resource links as described [here](https://docs.civicdb.org/en/latest/api/linking.html). In your example, this would be https://civicdb.org/links/variants/33 (please note the `links` portion of the URL). These style of urls are guaranteed by us to be available in any version of civic, even if the target page url format might change again in the future.
