### ISSUE TITLE
Oncogenic/Predisposing EID update with pos/neg axis for disease causality

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-v2#537]
In this figure from Alex Wagner, note how Predictive and Prognostic evidence have axes with opposing concepts, and a neutral term in the center.

<img width="708" alt="Screen Shot 2022-05-27 at 1 15 51 AM" src="https://user-images.githubusercontent.com/13948978/170646584-6137d094-b923-4749-bd98-f3f3d9282689.png">

Note how in CIViC for predictive evidence, approaching the center from the left yields "does not support sensitivity" annotation. 

<img width="1012" alt="Screen Shot 2022-05-27 at 1 54 27 AM" src="https://user-images.githubusercontent.com/13948978/170647434-6c081f14-d90d-41d0-a15c-fc4afc26ede3.png">

Updating the data model in CIViC for Predictive and Oncogenic EIDs would look as in this mock up below. 

<img width="790" alt="Screen Shot 2022-05-27 at 1 15 39 AM" src="https://user-images.githubusercontent.com/13948978/170647586-1e7a0596-fb3d-448c-b945-73b0c270bf7c.png">

Note that this image also contains the suggestion that a third Evidence Direction be added, but that **_has not yet been agreed on_**, while the adoption of Wagner's proposed model of `Predisposition`/`Protectiveness` and `Oncogenicity`/`Protectiveness` for Predisposing and Oncogenic EIDs was agreed on during a Friday meeting held in Winter 22.

**Comment by arpaddanos** [comment]
Should we go with the term Oncogenic, or find a different term for this EID type, like we moved away from using Pathogenic for Predisposing Evidence type?

**Comment by arpaddanos** [comment]
CIViC built into its data model that evidence was supposed to meet a bar before conclusion. The argument for introducing Inconclusive is to capture studies where neither supports or does not support was observed. So the idea that we should be cutting across all EID with a fundamental new change of Inconclusive Evidence Direction to capture evidence that gives no direction seems against the spirit of CIViC which was to have a higher bar for evidence. If there is no statement to make on the variant then it should not be curated. Just like we do not curate the observation of a variant in a tumor unless it meets the bar of interest in an SC-VCEP

**Comment by arpaddanos** [comment]
Oncogenicity is the Clinical Significance, Oncogenic is the EID and AID name

**Comment by obigriffith** [comment]
Just thinking about the potential for variants with evidence type of oncogenic and significance of "protectiveness". We don't have obvious examples of this yet. But, one could imagine a passenger somatic variant that modulates or mitigates in some way the oncogenic properties of a driver variant (e.g., in the same gene, pathway, etc). This is more easy to imagine with common polymorphism some protective effect but I don't see why it couldn't occur (by chance) with a somatic passenger variant.

**Comment by malachig** [comment]
https://lucid.app/lucidspark/23ae4dc2-a014-4e02-b259-366208a47407/edit?viewport_loc=-1426%2C-769%2C5376%2C2928%2C0_0&invitationId=inv_8a4a7a13-a05a-4608-a4ff-fef0890aa56f#

**Comment by arpaddanos** [comment]
There is a flaw in the overall logic of the new Predisposing EID type, which has been discussed before. The EID type describes predisposition on two axis: 

1. predisposition for protectiveness
2. predisposition for pathogenicity

therefore the Clinical Significance for Predisposing EIDs should be `Protectiveness` and `Pathogenicity`
