### ISSUE TITLE
Oncogenicity Assertions in CIViC V2

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-v2#538]
Related issue 537 on Oncogenic/Pathogenic [EID rework](https://github.com/griffithlab/civic-v2/issues/537) 

Using the model set by Predisposing Assertions, we will create an Oncogenicity Assertion. The Assertion will collect Oncogenic and Functional EIDs, as well as other types, to create an evaluation of variant Oncogenicity (conceptualized as variant ability to drive processes associated with Hallmarks of Cancer as defined by Hannahan and Weinberg). The Assertion will also leverage the recently published Standards for the classification of pathogenicity of somatic variants in cancer (oncogenicity): Joint recommendations of Clinical Genome Resource (ClinGen), Cancer Genomics Consortium (CGC), and Variant Interpretation for Cancer Consortium (VICC) for systematic assessment.

<img width="726" alt="Screen Shot 2022-05-27 at 2 21 45 AM" src="https://user-images.githubusercontent.com/13948978/170652225-32f83b03-d6c0-4e5e-9f9d-e9591a5a5b69.png">

A scale and codes are used to evaluate variant benign/oncogenic annotation.

<img width="785" alt="Screen Shot 2022-05-27 at 2 22 06 AM" src="https://user-images.githubusercontent.com/13948978/170652293-1f806813-a6c5-4178-8c1c-e24fc318dd96.png">

Among the most important unresolved issues for this Assertion are:

- Fields that will be supported in the Assertion
- Will Oncogenicity codes be added to supporting EIDs, or left in EID comments as currently?

<img width="882" alt="Screen Shot 2022-05-27 at 2 21 55 AM" src="https://user-images.githubusercontent.com/13948978/170652280-4365cd55-7972-448c-87ac-b29fc42202ca.png">

**Comment by arpaddanos** [comment]
Important note on the parallel development of Oncogenic EIDs (See Issue 537) and Oncogenic Assertions. The proposed Clinical Significance for Oncogenic EIDs will not be reflected in the first iteration of the CIViC Oncogenicity Assertion, as there are no published guidelines for the `Protective` axis of the the `Disease Causality` scale. Figure below summarizes this.
<img width="1008" alt="Screen Shot 2022-05-27 at 2 47 19 AM" src="https://user-images.githubusercontent.com/13948978/170654965-ae1f204a-3677-4c3d-a4b7-0f07f3cee389.png">

**Comment by arpaddanos** [comment]
Note that if Oncogenicity codes are added to Oncogenic EIDs, then a corresponding addition of ACMG codes to Predisposing EIDs should be considered.

**Comment by kkrysiak** [comment]
Assertion Oncogenicity codes should consider new rules being used for NTRK fusions. Basically, in addition to the oncogenicity codes for snvs/indels, we should consider support for new fusion rules in development (this may be a future direction).

**Comment by arpaddanos** [comment]
That's right @kkrysiak. It is something we should do and also I agree it is a future direction. It should be implemented once the NTRK SC-VCEP has published its guidelines, since I think that is part of the roadmap.

**Comment by malachig** [comment]
https://lucid.app/lucidspark/23ae4dc2-a014-4e02-b259-366208a47407/edit?viewport_loc=-1426%2C-769%2C5376%2C2928%2C0_0&invitationId=inv_8a4a7a13-a05a-4608-a4ff-fef0890aa56f#
