### ISSUE TITLE
Table contents take up more width once filtered to fit on one page

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-v2#542]
When filtering a table so that the result set fits on one page, the table contents get redrawn to take up the full width including the space previously occupied by the scroll bar. The table header doesn't get redrawn so the columns no longer line up

https://user-images.githubusercontent.com/6617192/171727066-d7020be2-d985-4e93-a88f-2b49fcfea4a9.mov

**Comment by acoffman** [comment]
(Fixed by josh's table updates)
