### ISSUE TITLE
Duplicate elements in suggestions drop-down select

### ISSUE THREAD

**Issue by creisle** [griffithlab/civic-v2#545]
When I enter a new evidence item and start typing the gene name, multiple copies of the same gene show up in the list

![image](https://user-images.githubusercontent.com/4342641/172229317-e0195c9d-d514-4e8f-b97a-6218399b1477.png)

**Comment by acoffman** [comment]
For this typeahead w first match on entrez symbols and, if we don't have enough results to fill the list, match on aliases. We were failing however to de-duplicate those matches, so genes that matched on symbol and on alias would appear twice. I've opened a PR to address this. It will go out in the next release!
