### ISSUE TITLE
Feature Request: Focus on clicking Specify a Gene

### ISSUE THREAD

**Issue by creisle** [griffithlab/civic-v2#547]
When I click specify a gene, I would like to be able to start typing without having to also tab and/or click into the input box

![image](https://user-images.githubusercontent.com/4342641/172235024-26d04ce5-8132-4ded-8b6e-6e801041ff76.png)

If I click the "+ specify a gene" and then start to type it does not type in the box unless i click on the newly shown input box before I start typing

![image](https://user-images.githubusercontent.com/4342641/172235176-cba77351-6341-4e51-a3e5-ec8b4d9f6bef.png)

It would simplify the process if I didn't have to do the extra click

**Comment by acoffman** [comment]
Agreed this would be better behavior. I've opened a PR that includes this and it'll go out in the next release!
