### ISSUE TITLE
Add ability to merge User Profiles

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#578]
With multiple OAuth options, this happens. Either a new mechanism in the Admin console the way we have traditionally done this, or if possible, allow users to do so on their own.

**Comment by jsaliba10** [comment]
While trying to clean up some one the clingen user profiles, I have found a few that have multiple log ins that would be great to merge.

**Comment by acoffman** [comment]
This is now available in the admin interface (finally!)
