### ISSUE TITLE
Variant table text search failing for -

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#584]
Searching for the specific character `-` returns no results. That character should return results. Example variant: https://civicdb.org/variants/3049/summary
![Screen Shot 2022-07-21 at 2 05 32 PM](https://user-images.githubusercontent.com/8527125/180296031-b96b4dc4-8a49-4468-847e-b200e79ba161.png)
![Screen Shot 2022-07-21 at 2 05 38 PM](https://user-images.githubusercontent.com/8527125/180296033-cad28900-741a-4990-8af9-f9b5b71ef5de.png)

**Comment by malachig** [comment]
This is also failing when you enter "::" which would be a convenient way to find fusion variants.  

Finding fusion variants is currently difficult in CIViC V2.  We don't have advanced search yet, we don't show variant type in the variant table, and the above search does not work.

**Comment by acoffman** [comment]
This is because these queries are left anchored ie `^searchterm*`

We can switch it to be wildcards on both sides, which will be a little slower but perhaps desirable?
