### ISSUE TITLE
Quick search shows AID repeats

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#615]
<img width="327" alt="Screen Shot 2022-08-28 at 10 40 31 AM" src="https://user-images.githubusercontent.com/8527125/187082449-19f597c0-4f5e-4410-8757-61e0d4593b23.png">

I had planned to show off entity searches but it shows AID22 three times in a row. Some deduplicating would help.

**Comment by susannasiebert** [comment]
I believe this has been fixed in commit 1ea3e257f206b726912e250f08b369d89d0ebbfa, which will go out with the next release

**Comment by susannasiebert** [comment]
You can test your search on the staging box to get a better screenshot.

**Comment by kkrysiak** [comment]
Wonderful. Thank you!
