### ISSUE TITLE
Add mychem.info to drug pages

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#642]
Now that drugs are a first-class entity, we can add more information from outside sources to their individual pages the way we do for Variants and Genes. 

mychem.info includes additional fields we should further investigate including `fda_epc` and `fda_moa`.

**Comment by susannasiebert** [comment]
@kkrysiak it would be great to get a list of fields we'd like to import.

**Comment by kkrysiak** [comment]
I would recommend the following (to be discussed at next CIViC meeting):
- FDA: 
--`fda_epc` and `fda_moa` all 3 versions of each
- CHEBI: (https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:45783)
--`chebi.id` (ideally link to chebi example) `chebi.definition` 
- CHEMBL: (https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL941/)
-- drug mechanisms `chembl.drug_mechanisms.target_chembl_id` `chembl.drug_mechanisms.target_name` but only if we can restrict to these mechanisms provided by an FDA reference `chembl.drug_mechanisms.mechanism_refs.FDA`
-- First approval `chembl.first_approval`
-- Molecule type `chembl.molecule_type`
-- CHEMBL ID? Not sure if this is the correct field but link to CHEMBL page `chembl.molecule_chembl_id`

**Comment by acoffman** [comment]
Example request: `https://mychem.info/v1/query?q=unii.ncit:"C1723"`

**Comment by acoffman** [comment]
>     * CHEMBL: (https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL941/)
>       -- drug mechanisms `chembl.drug_mechanisms.target_chembl_id` `chembl.drug_mechanisms.target_name` but only if we can restrict to these mechanisms provided by an FDA reference `chembl.drug_mechanisms.mechanism_refs.FDA`

cant find an example of this yet, but we can revisit if we find one. all the rest of the fields are implemented
