### ISSUE TITLE
Add provenance / events around creation of variants

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-v2#664]
Currently when an editor creates a variant directly or from the add evidence form, there is no tracking around who created it and when.  

When a variant is created directly without an evidence submission it really feels like it comes out of nowhere.  In light of this and with our plans to allow deprecation of variants, it would be nice to always know the user who created each variant.

Action items:
- Add tracking to creation of variants to store the user/org and time of creation.  
- Backfill existing variants based on the first associated evidence item.
- For variants that can not be backfilled according to this approach, assign to an existing editor.  Provide a list to us and we can choose who to take ownership of these.

**Comment by acoffman** [comment]
- [ ] Add new action type to Event enum
- [ ] Support new action type on event feed, filters, etc
- [ ] Display "created by" (verbiage?) on Variant page
- [ ] Create event on variant creation
