### ISSUE TITLE
Filtering by MP name in the Evidence grid not working as expected

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#698]
It seems like the search/filter box for MPs at the top of the Evidence grid isn't recognizing the first or last character that is entered.

For example, "FGFR" also finds "EGFR" in addition to MPs with "FGFR", "FGFR3" also finds "FGFR1". 
You can even enter something that doesn't exist like "TGFR" and it will find "EGFR" and "FGFR".

![image](https://user-images.githubusercontent.com/3093548/211910555-61a6cad1-de85-49ae-a2a7-a78c07a1be4f.png)

![image](https://user-images.githubusercontent.com/3093548/211910841-2beff379-3795-416b-b1fe-51c0e9889c6e.png)

![image](https://user-images.githubusercontent.com/3093548/211910464-f68380bd-dacd-45ed-a125-273548f513ec.png)

**Comment by acoffman** [comment]
The default behavior of our elasticsearch library was to return results with an edit distance of 1 from your search query to accommodate typos and misspellings, while this may be desirable for other types of search, its confusing for table filtering. 

#701 updates the search params to only try for misspelling matches if there are no exact matches.
