### ISSUE TITLE
Predisposition icon not displaying in Evidence grid

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#717]
<img width="857" alt="Screen Shot 2023-01-20 at 12 03 13 PM" src="https://user-images.githubusercontent.com/8527125/213774080-13a3bf39-da93-4831-b573-a0ab4ff7d198.png">

From this page: https://civicdb.org/sources/2240/summary

**Comment by cgrisdale** [comment]
Also noticed when looking through Predisposing evidence that several other icons (plus, minus, heart, strikethrough) are also displaying 'Predisposition' when you hover over.

**Comment by acoffman** [comment]
This is deployed and should all be corrected now.
