### ISSUE TITLE
Internal Server Error in genes API call response

### ISSUE THREAD

**Issue by sundarg4** [griffithlab/civic-v2#721]
While running the Genes query in the [GraphQL ](https://civicdb.org/api/graphiql) interface we are getting an internal server error. Please find the request and response below,

**Query Request:**

query Genes {
  genes(first: 10) {
    totalCount
  }
}

**Response:**
{
  "status": 500,
  "error": "Internal Server Error"
}

**Comment by acoffman** [comment]
Apologies for the issue, a new release is out which should resolve it for you. Thanks for your interest in CIViC!

**Comment by sundarg4** [comment]
@acoffman Thank you so much for your swift response and fix :)
