### ISSUE TITLE
Comment referencing search shows not found when it is

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-v2#730]
<img width="832" alt="Screen Shot 2023-02-03 at 9 41 50 AM" src="https://user-images.githubusercontent.com/8527125/216645201-d57bd7c5-6a3d-4b8e-8f73-c2145ae00f00.png">
<img width="836" alt="Screen Shot 2023-02-03 at 9 41 56 AM" src="https://user-images.githubusercontent.com/8527125/216645219-209a52d8-cb20-4efc-a61b-7a41461bf526.png">

Also reported by @obigriffith

**Comment by acoffman** [comment]
@susannasiebert had actually already fixed it and we just rolled it out to prod now. It should be working now!
