### ISSUE TITLE
Mixed->Combined Variant Origin

### ISSUE THREAD

**Issue by acoffman** [griffithlab/civic-v2#821]
Used to describe an MP where the constituent variants have differing origins.

- [x] Update docs
- [x] rename enum
- [x] update tooltips
- [ ] Do not allow this to be selected when the user has chosen a single variant MP.
- [x] Add rails validation
- [x] Check to make sure we don't have existing EIDs/Assertions where Mixed is selected for a single variant MP
- [x] Add Combined to EID table filters

**Comment by susannasiebert** [comment]
Also add rails validation for this case.
