### ISSUE TITLE
Cannot add DOID to existing term that doesn't have DOID

### ISSUE THREAD

**Issue by refu6enik** [griffithlab/civic-v2#888]
There does not appear to be a way to add a DOID to a term that does not have a DOID. You can only use an existing term or create a term with a name that has not already been used.

Villous Adenoma (https://civicdb.org/diseases/3075/summary) needs to be updated to have DOID:0050869 (see https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/main/src/ontology/doid.obo).

**Comment by acoffman** [comment]
Thanks for bringing this to our attention! I confirmed with one of our editors that this is indeed the correct DOID for this disease term and I've populated the field.

We'll take a look and see why this wasn't automatically populated from our DO importer.
