### ISSUE TITLE
Unable to see user profile

### ISSUE THREAD

**Issue by sumirp** [griffithlab/civic-v2#899]
steps to reproduce.
1. Log-In to CIVic knowledgebase
2. select Your Profile from the dropdown under the username icon
3. A blank page not showing the user activity.

<img width="960" alt="Screenshot 2023-10-03 111844" src="https://github.com/griffithlab/civic-v2/assets/46551795/72acc2d2-8c32-409c-9c97-2e2277d401d0">

**Comment by acoffman** [comment]
Hi @sumirp, thanks for reporting this issue! We have a fix going live on staging currently and then we'll push it out to production shortly.

**Comment by sumirp** [comment]
Thank you @acoffman for your response!
