### ISSUE TITLE
Update DGIdb gene link-out from gene page

### ISSUE THREAD

**Issue by jsstevenson** [griffithlab/civic-v2#947]
With the impending switch over to the new DGIdb frontend, the existing link to the DGIdb entry for a given gene will break. Now, gene records are identified in a URL by their normalized concept ID, not their Entrez symbol, e.g. [https://beta.dgidb.org/genes/hgnc:391](https://beta.dgidb.org/genes/hgnc:391) vs [https://dgidb.org/genes/AKT1](https://dgidb.org/genes/AKT1). 

You could just link to the corresponding HGNC ID if you have that under the hood, but normalized genes are [not guaranteed to use concept IDs from a specific namespace](https://gene-normalizer.readthedocs.io/en/latest/normalizing_data/normalization.html#building-normalized-concepts-and-records). It might be safest and simplest to just link to the search results for a given gene, e.g. [https://beta.dgidb.org/results?searchType=gene&searchTerms=AKT1](https://beta.dgidb.org/results?searchType=gene&searchTerms=AKT1).

**Comment by acoffman** [comment]
We do have Entrez IDs under the hood, but it looks like the `entrez:<id>` format does not work (at least for this Gene) so perhaps you're right that the search result link makes the most sense.
