### ISSUE TITLE
Error revising variant alises

### ISSUE THREAD

**Issue by cgrisdale** [griffithlab/civic-v2#987]
When trying to submit a revision to a variant to remove aliases I am either getting an error (see below) or the revision is made but the aliases I removed are not being selected to be deleted. When deleting multiple aliases sometimes some of the aliases are selected for deletion but this seems to vary each time I try submitting a revision.

![image](https://github.com/griffithlab/civic-v2/assets/3093548/0356d09b-f763-4755-b19a-34986eaef216)

**Comment by acoffman** [comment]
Thanks for the report @cgrisdale, we've tracked down the issue and should have a fix going out later today! I'll follow up here when its live.

**Comment by acoffman** [comment]
A fix for this is live. Thanks again!

**Comment by cgrisdale** [comment]
Thanks for the quick work!
