### ISSUE TITLE
Improve comments functionality

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-v2#996]
In adding some comments to a variant page in CIViC v2 I noticed several limitations compared to what we used to be able to do in CIViC v1.

https://civicdb.org/variants/4415/comments

- [x]  Markdown is no longer rendered
- [x]  The "Preview" view doesn't seem to do anything.
- [x]  You can no longer expand the size of the comment window.  For complex comments this makes it hard to check for errors/consistency. 
- [x]  A user can no longer delete their own comment.  If you make any mistakes, all you can do is leave another comment. 
- [x]  The comments page in the admin interface gives an error: HTTP ERROR 500.  So you can't delete a messy comment there either.

**Comment by acoffman** [comment]
All of these points are addressed in #1108 and will be fixed when it is deploy!
